### ISSUE TITLE
Make failing with error /bin/sh: 1: /root/volume-replication-operator/bin/controller-gen: not found

### ISSUE THREAD

**Issue by saranyareddy24** [kube-storage/volume-replication-operator#138]
I tried running make all, it fails with the below error.
```
/bin/sh: 1: /root/volume-replication-operator/bin/controller-gen: not found
make: *** [Makefile:94: generate] Error 127
```
I also tried running make controller-gen, saw the above issue even after successful build of controller-gen.

```
GOPATH=/usr/local/go/bin
GOBIN=/usr/local/go/bin/bin
```

Make is checking in the `$pwd/bin` path for the controller-gen binary where it is not present.

When I ran manully `go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1` , I noticed that the binary is downloaded to `$GOBIN/`

```
~/volume-replication-operator# ls -lrt /usr/local/go/bin/bin/
total 20560
-rwxr-xr-x 1 root root 21049684 Jun  5 16:43 controller-gen
```

Should we make modification in the Makefile to point to `GOBIN` path instead of the` $pwd/bin` path.
`CONTROLLER_GEN = $(shell pwd)/bin/controller-gen`

**Comment by Madhu-1** [comment]
@saranyareddy24 this operator is deprecated , please use kubernetes-csi-addons project as an alternative https://github.com/csi-addons/volume-replication-operator/issues/136
