### ISSUE TITLE
Rename VolRep `Spec.ImageState` to `Spec.VolumeState`

### ISSUE THREAD

**Issue by ShyamsundarR** [kube-storage/volume-replication-operator#46]
Currently the [spec](https://github.com/kube-storage/volume-replication-operator/blob/473b43db4d6bf121b741610cb3527d0240509e6f/api/v1alpha1/volumereplication_types.go#L55-L58) names the state of the volume as `imageState`. Image gives the connotation that the volume is backed by an image, which is true for block based RWO providers, it hence maybe better to refer to this as `volumeState` instead to stay generic.

**Comment by vdeenadh** [comment]
Another suggestion for imageState is replicationState, as defined in the VolRep SHIM: https://pkg.go.dev/github.com/shyamsundarr/volrep-shim-operator@v0.0.0-20210310121354-2f9f9b83efb6/api/v1alpha1?utm_source=gopls#ReplicationState

**Comment by Madhu-1** [comment]
@vdeenadh Thanks for the suggestion!
